
-- SELECT de usuários com nome diferente do interessado
SELECT USU.NMUSUARIO AS NOME_SEGURANÇA, TNI.NMSUJEITO AS NOME_SUJEITO, TNI.NUIDENTSUJEITO AS CPF 
FROM ESEGUSUARIO USU 
INNER JOIN ECDTSUJEITO TNI ON TNI.NUIDENTSUJEITO = USU.NUCPFCNPJ 
WHERE  USU.NMUSUARIO != TNI.NMSUJEITO AND USU.FLHABILITADO = 'S';

-- Update usuários com nome SEG diferente do interessado
UPDATE USU
SET USU.NMUSUARIO = TNI.NMSUJEITO
FROM ESEGUSUARIO USU
INNER JOIN ECDTSUJEITO TNI ON TNI.NUIDENTSUJEITO = USU.NUCPFCNPJ WHERE  USU.NMUSUARIO != TNI.NMSUJEITO AND LEN(USU.CDUSUARIO) > 10 AND USU.FLHABILITADO = 'S';

-- Modelo de delete favoritos
DELETE FROM ECPAPROCESSOFAVORITO WHERE CDUSUARIO = :cdusuario AND NMPROCESSO : 

